version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /home/ec2-user/flask-app

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
